commerce_payment.commerce_payment_gateway.plugin.reepay_offsite:
  type: commerce_payment_gateway_configuration
  mapping:
    public_key:
      type: string
      label: 'Public key'
    private_key:
      type: string
      label: 'Private key'
    webhook_key:
      type: string
      label: 'Webhook key'
    redirect_method:
      type: string
      label: 'Redirect method'
